export enum UIPlaygroundAssetIds {
  CustomButtonIdle = "UIPlayground.CustomButton.Idle",
  CustomButtonHover = "UIPlayground.CustomButton.Hover",
  CustomButtonPressed = "UIPlayground.CustomButton.Pressed",
  CustomButtonDisabled = "UIPlayground.CustomButton.Disabled",
  CustomSliderTrack = "UIPlayground.CustomSlider.Track",
  CustomSliderFill = "UIPlayground.CustomSlider.Fill",
  CustomSliderThumb = "UIPlayground.CustomSlider.Thumb",
  CustomRadioUnselected = "UIPlayground.CustomRadio.Unselected",
  CustomRadioSelected = "UIPlayground.CustomRadio.Selected",
  CustomToggleTrackOn = "UIPlayground.CustomToggle.TrackOn",
  CustomToggleTrackOff = "UIPlayground.CustomToggle.TrackOff",
  CustomToggleThumb = "UIPlayground.CustomToggle.Thumb",
  CustomBackground = "UIPlayground.CustomBackground",
  CustomDropdownHeader = "UIPlayground.CustomDropdown.Header",
  CustomDropdownList = "UIPlayground.CustomDropdown.List",
  CustomDropdownItemIdle = "UIPlayground.CustomDropdown.ItemIdle",
  CustomDropdownItemHover = "UIPlayground.CustomDropdown.ItemHover",
  CustomDropdownItemSelected = "UIPlayground.CustomDropdown.ItemSelected",
  CustomDropdownChevron = "UIPlayground.CustomDropdown.Chevron",
  CustomListItemIdle = "UIPlayground.CustomList.ItemIdle",
  CustomListItemHover = "UIPlayground.CustomList.ItemHover",
  CustomListItemSelected = "UIPlayground.CustomList.ItemSelected",
  CustomScrollViewTrack = "UIPlayground.CustomScrollView.Track",
  CustomScrollViewThumb = "UIPlayground.CustomScrollView.Thumb",
}
